### ISSUE TITLE
Asterisk 13 Support

### ISSUE THREAD

**Issue by number5** [adhearsion/adhearsion#544]
Try to get 2.6.0 work with Asterisk 13, I can see all the AMI events passing through to Adhearsion in the logs, but none of the controllers works, my guess is the current adhearsion/punchblock do not support AMI 2 protocol.

Is there any plan to support Asterisk 13?

**Comment by benlangfeld** [comment]
Support for Asterisk 12/13 is indeed missing. No-one has properly tested / reported the full set of bugs or worked on fixing them. Contributions, even if just of properly formatted bug reports (see http://adheres ion.com/docs/dealing-with-bugs), are welcome.

**Comment by number5** [comment]
Cool, will get bug reports ready once I've restored the testing environment.

**Comment by benlangfeld** [comment]
Basic Asterisk 13 support is provided in Punchblock 2.7.0. See https://github.com/adhearsion/punchblock/issues/245 for details. If anything remains broken, please report individually and in full, referencing that issue.
