### ISSUE TITLE
connection to freeswitch fails when using jruby

### ISSUE THREAD

**Issue by pdamer** [adhearsion/adhearsion#548]
using adhearsion 2.6 with jruby 1.7.19 the connection to freeswitch hangs before the auth is sent.  It works fine on MRI 2.2.1 and 1.9.3.  I also tried jruby 1.7.12 with no luck.

Log output that compares MRI with jruby is here:
https://gist.github.com/pdamer/f165c857eae5e157da71

Here is the thread stacktrace of the connection attempt:
```
/Users/pdamer/.gem/jruby/1.9.3/gems/eventmachine-1.0.7-java/lib/jeventmachine.rb:112:in `run_machine'
/Users/pdamer/.gem/jruby/1.9.3/gems/eventmachine-1.0.7-java/lib/eventmachine.rb:187:in `run'
/Users/pdamer/.gem/jruby/1.9.3/gems/punchblock-2.6.0/lib/punchblock/connection/xmpp.rb:88nnect'
/Users/pdamer/.gem/jruby/1.9.3/gems/punchblock-2.6.0/lib/punchblock/connection/xmpp.rb:83:in `run'
/Users/pdamer/.gem/jruby/1.9.3/gems/punchblock-2.6.0/lib/punchblock/client.rb:13:in `run'
/Users/pdamer/.gem/jruby/1.9.3/gems/adhearsion-2.6.0/lib/adhearsion/punchblock_plugin/initiali106:in `connect_to_server'
/Users/pdamer/.gem/jruby/1.9.3/gems/adhearsion-2.6.0/lib/adhearsion/punchblock_plugin/initiali95:in `connect'
/Users/pdamer/.gem/jruby/1.9.3/gems/adhearsion-2.6.0/lib/adhearsion/foundation/exception_hand5:in `catching_standard_errors'
/Users/pdamer/.gem/jruby/1.9.3/gems/adhearsion-2.6.0/lib/adhearsion/punchblock_plugin/initiali95:in `connect'
/Users/pdamer/.gem/jruby/1.9.3/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/Users/pdamer/.gem/jruby/1.9.3/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `create_with_logging_context'
```

**Comment by benlangfeld** [comment]
I don't see that stack trace in your logs. Where did it come from?

**Comment by pdamer** [comment]
I dumped it from the global list of threads:

> AHN> Thread.list.each do |thread|
> AHN?   STDERR.puts "Thread-#{thread.object_id.to_s(36)}"  
> AHN?   STDERR.puts thread.backtrace.join("\n    \\_ ")  
> AHN? end```

**Comment by benlangfeld** [comment]
Perhaps you could use `bundle open` to add `logger.error e` after this line: https://github.com/adhearsion/adhearsion/blob/develop/lib/adhearsion/punchblock_plugin/initializer.rb#L107

**Comment by pdamer** [comment]
Here are the results of logger.error e

    [2015-05-04 14:37:42.650] INFO  Adhearsion::PunchblockPlugin::Initializer: Starting connection to server
    [2015-05-04 14:37:42.747] TRACE Punchblock::Connection::XMPP: USING JID: adhearsion@***IP***/
    [2015-05-04 14:37:42.775] TRACE Punchblock::Connection::XMPP: SENDING: (/Users/pdamer/.gem/jruby/1.9.3/gems/blather-1.0.0/lib/blather/stream/client.rb:12:in `start') <stream:stream to='***IP***' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>
    [2015-05-04 14:37:42.852] TRACE Punchblock::Connection::XMPP: RECEIVING (stream) <stream:stream from="***IP***" id="e80c76e9-3499-4662-87c1-269e04231708" lang="en" version="1.0" xmlns:db="jabber:server:dialback" xmlns:stream="http://etherx.jabber.org/streams"/>
    [2015-05-04 14:37:42.860] TRACE Punchblock::Connection::XMPP: RECEIVING (features) <stream:features xmlns:stream="http://etherx.jabber.org/streams"><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism></mechanisms></stream:features>
    AHN> 
    AHN> [2015-05-04 14:38:42.817] ERROR Adhearsion::PunchblockPlugin::Initializer:     <Punchblock::DisconnectedError> Stream timed out after 60 seconds.
	/Users/pdamer/.gem/jruby/1.9.3/gems/punchblock-2.6.0/lib/punchblock/connection/xmpp.rb:90:in `connect'
	/Users/pdamer/.gem/jruby/1.9.3/gems/punchblock-2.6.0/lib/punchblock/connection/xmpp.rb:83:in `run'
	/Users/pdamer/.gem/jruby/1.9.3/gems/punchblock-2.6.0/lib/punchblock/client.rb:13:in `run'
	/Users/pdamer/.gem/jruby/1.9.3/gems/adhearsion-2.6.0/lib/adhearsion/punchblock_plugin/initializer.rb:106:in `connect_to_server'
	/Users/pdamer/.gem/jruby/1.9.3/gems/adhearsion-2.6.0/lib/adhearsion/punchblock_plugin/initializer.rb:95:in `connect'
	/Users/pdamer/.gem/jruby/1.9.3/gems/adhearsion-2.6.0/lib/adhearsion/foundation/exception_handler.rb:5:in `catching_standard_errors'
	/Users/pdamer/.gem/jruby/1.9.3/gems/adhearsion-2.6.0/lib/adhearsion/punchblock_plugin/initializer.rb:95:in `connect'
	org/jruby/RubyProc.java:271:in `call'
	/Users/pdamer/.gem/jruby/1.9.3/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `create_with_logging_context'

**Comment by pdamer** [comment]
This seems to be caused by whatever is behind this bug in blather: https://github.com/adhearsion/blather/issues/145

Downgrading nokogiri to 1.6.1 seems to have fixed my issue.

**Comment by mstate** [comment]
After some investigation and think I've isolated the issue (don't know how to fix it though).  I've updated [adhearsion/blather#145](https://github.com/adhearsion/blather/issues/145) with the details.
