### ISSUE TITLE
Crash on originating outbound call with adhearsion 2.6, jruby 1.7.20 and activesupport 4.2.1. MRI 2.1.5 works.

### ISSUE THREAD

**Issue by ggayan** [adhearsion/adhearsion#549]
Hey people, I was performing an upgrade on our adhearsion app and a simple originate explodes when using jruby. MRI 2.1.5 works for the same bundled gems.

I've added all the details to the linked gist file. Pinning activesupport to version 4.1.0 solved the issue for us. I think it is healthy to discuss this case though, so we can save some work for other adhearsion fellows.

https://gist.github.com/ggayan/5c90f10c59c4c747b6be

**Comment by benlangfeld** [comment]
Lucky you - you found a bug in JRuby. You should report it at http://github.com/jruby/jruby. Please link to this issue :)

**Comment by ggayan** [comment]
Yay, on my way :)

**Comment by ggayan** [comment]
I guess that I was giving a wrong argument to `Timeout`, which expects a Fixnum or a Float. Still, it is what we see in some `dial` examples: 
```ruby
dial %w{SIP/jay-desk-650 SIP/jay-desk-601 SIP/jay-desk-601-2}, :for => 15.seconds, :from => my_callerid
```
as seen in http://www.rubydoc.info/github/adhearsion/adhearsion/Adhearsion/CallController/Dial#dial-instance_method

Maybe it should be recommended to use something like `15.seconds.to_i`, isn't it?

**Comment by benlangfeld** [comment]
As per the JRuby issue linked above, I still believe this is an issue in JRuby. That ticket has been re-opened, and I'm going to close this one.
