### ISSUE TITLE
Merge Punchblock and Adhearsion

### ISSUE THREAD

**Issue by benlangfeld** [adhearsion/adhearsion#558]
It is likely that at this stage it is worth considering merging Punchblock into Adhearsion core rather than remaining a separate dependency.

Arguments for:

* Users never know when to file issues against Adhearsion or Punchblock
* Adhearsion and Punchblock's development cycles are linked such that they may as well have one version number. See https://github.com/adhearsion/adhearsion/pull/527, https://github.com/adhearsion/adhearsion/blob/develop/lib/adhearsion/generators/app/templates/Gemfile.erb#L5-L9, etc
* Writing Adhearsion apps requires knowledge of Punchblock. See https://github.com/adhearsion/adhearsion/blob/develop/lib/adhearsion/call_controller/output.rb#L21, https://github.com/adhearsion/adhearsion/blob/develop/lib/adhearsion/call_controller/output.rb#L133, https://github.com/adhearsion/adhearsion/blob/5019eba159a0f84dbc5d74064e1b40a4ddabaa5c/lib/adhearsion/call_controller/input.rb#L31-L32, https://github.com/adhearsion/adhearsion/blob/5019eba159a0f84dbc5d74064e1b40a4ddabaa5c/lib/adhearsion/call_controller/record.rb#L56.
* Punchblock is not used by anyone else anyway

Arguments against:

* Punchblock is used by software other than Adhearsion applications. At this time, we don't know what is actively using it. An old project to use Rayo as an interface for an integration testing tool (cucumber-voip) used it, but that's long dead.
* Adhearsion should remain Rayo-only in core. This is an ideological argument only.
* Punchblock is a cool name and we don't want it to go away

**Comment by bklang** [comment]
Generally, I think this is a win for the reasons you explained.  I'd like to dig into the arguments against:

Arguments against:

> * Punchblock is used by software other than Adhearsion applications
Who? What?

> * Adhearsion should remain Rayo-only in core
I understand the argument for this being keeping the Adhearsion codebase simpler, but why else should this be the case? We can still define a Rayo-like API between the Translator layer (with a noop to Rayo on XMPP, and actual translation when headed to AMI). Does that not satisfy this?

> * Punchblock is a cool name and we don't want it to go away
This is not a good reason to keep a project alive, though I do agree about the name :)

**Comment by benlangfeld** [comment]
I've updated those points above in response to your questions.

**Comment by benlangfeld** [comment]
Closing in favour of https://github.com/adhearsion/adhearsion/pull/561
