### ISSUE TITLE
Integrate a web server (Virginia) into Adhearsion Core

### ISSUE THREAD

**Issue by benlangfeld** [adhearsion/adhearsion#559]
This is intended to provide a baseline for modules to build upon in order to act as a recommended method of building a control API for an Adhearsion application, as well as for serving TTS and ASR documents.

**Comment by bklang** [comment]
:+1:. I'd like to add that I support @JustinAiken's suggestion that it needs to be possible to turn it off as well.

**Comment by benlangfeld** [comment]
Closing in favour of #569
