### ISSUE TITLE
Ability to work with multiple PBX on single code

### ISSUE THREAD

**Issue by ik5** [adhearsion/adhearsion#576]
One of the issues with ahn, is that it can work only with a single PBX connection, for example a single Asterisk or a single Freeswitch.

But many times we have several PBX (sometimes some are Asterisk and some are Freeswitch) that actually requires the same system.

If there will be more then a single PBX to the same code (I wonder if Ruby will be able to handle so many requests), it can allow a single application to work on more then on PBX at the same time.

There should be a plan also for a load balancing of some sort with the actor model, so if something does not respond, it can move to a new PBX, and if a PBX is unable to communicate with ahn, that it can access to additional copies of ahn

**Comment by benlangfeld** [comment]
The big picture plan here is Rayo, and specifically the fact that it was designed with clustering in mind. You might be interested in reading the latest version of [the specification](http://xmpp.org/extensions/xep-0349.html) or looking at some of the [materials prepared for explaining it](https://github.com/rayo/rayo-server/wiki/Clustering) as envisioned by the Tropo team.

@crienzo even started on an implementation of a Gateway as an ejabberd module. You can find it [in the FreeSWITCH source tree](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse/src/mod/event_handlers/mod_rayo/gateway), but I'm not sure how complete it is and if it even works.

**Comment by crienzo** [comment]
Note- with AHN and FS you can currently point multiple AHN clients to a single FS.  Each AHN could have a different username if you wish to route calls to specific AHN clients via the dialplan.  If you want to distribute calls to multiple AHN clients, you can do all at once (according to spec), random distribution w/ failover, or first client w/ failover.

Many AHN to many FS was attempted with ejabberd module, but that effort stalled as we didn't have a real need for it.

**Comment by benlangfeld** [comment]
Closing this on the grounds of "Rayo is the answer".
