### ISSUE TITLE
Website domain name expired

### ISSUE THREAD

**Issue by MichaelVessia** [adhearsion/adhearsion#584]
The website is heavily referenced in the readme and wiki, but is currently inaccessible.  Is this information hosted elsewhere, or are there plans to get it back up and running?

**Comment by bklang** [comment]
Thanks for the report. We are aware of this, but unfortunately are having trouble getting access to the registrar (the domain was registered by people who are no longer active on the project).  We'll have it back online as quickly as possible.

**Comment by bklang** [comment]
@MichaelVessia I should have mentioned earlier, you can also get at the website temporarily via https://adhearsion-website-cedar.herokuapp.com.  Sorry for the inconvenience - we're working on it!

**Comment by MichaelVessia** [comment]
Thanks, and good luck getting it back online.

**Comment by benlangfeld** [comment]
And it's back. Sorry it took so long guys!
