### ISSUE TITLE
Can't add keys during iteration in 3.0

### ISSUE THREAD

**Issue by mstate** [adhearsion/adhearsion#589]
I'm seeing:
```
RuntimeError: can't add a new key into hash during iteration
```
while trying to add a call into Calls in Adhearsion 3.0 (develop branch) running against ruby-head.

Full backtrace can be seen at:
http://pastebin.com/xKe5ydzb

Could the offending lines in the Calls class be:
```
    def remove_inactive_call(call)
      if call_is_dead?(call)
        call_id = key call
        delete call_id if call_id

        remove_call_uri call
      elsif call.respond_to?(:id)
        delete call.id
        remove_call_uri call
      else
        call_actor = delete call
        remove_call_uri call_actor
      end
    end
```
Here the line:
```
call_id = key call
```
requires iteration over the values of the hash.

Similarly,
```
    def remove_call_uri(call)
      uri = by_uri.key call
      by_uri.delete uri if uri
    end
```
must also iterate.

Perhaps this is not the iteration that Ruby is complaining about, but it certainly looks like iteration.

From a performance perspective,
```
uri = by_uri.key call
```
will slow linearly with the number of calls in by_uri.

I assume that there's a reason we call call.id directly to find the key.  What about using the call.object_id as the key?

**Comment by mstate** [comment]
I've synchronized the key call with @mutex and have not seen the error again.   I'll submit a pull request.

**Comment by emcgee** [comment]
@mstate Did you have a PR to submit for this? We've seen it occasionally as wel.
