### ISSUE TITLE
USR1 is not supported on JRuby

### ISSUE THREAD

**Issue by vangberg** [adhearsion/adhearsion#599]
Reference: https://github.com/adhearsion/adhearsion/commit/c4d5d35ab48e1e6480297874ffc8a495fe04d00d

This doesn't work on JRuby/JVM and prints a warning:

```
The signal USR1 is in use by the JVM and will not work correctly on this platform
```

Maybe we could use `ABRT` instead? Does `Process.exit(1)` accomplish anything that `kill -9` doesn't?

**Comment by benlangfeld** [comment]
We already use `ABRT` a few lines up. We should switch `USR1` for `USR2`.

**Comment by bklang** [comment]
@vangberg the `force_stop` attempts to terminate active calls so they don't get orphaned in the telephony engine. For FreeSWITCH this shouldn't be a big deal (mod_rayo will eventually clean up), but for Asterisk, not cleaning up results in calls that have no owner and never time out.

**Comment by bklang** [comment]
Then I go back and look at the implementation and realize that's not the actual behavior we have now, though I'm pretty sure it's what we intended.

**Comment by benlangfeld** [comment]
That's the start of the shutdown process initiated by SIGINT and SIGTERM. SIGABT is intended for an abrupt stop.
