### ISSUE TITLE
Consistent handling for call start time

### ISSUE THREAD

**Issue by bklang** [adhearsion/adhearsion#601]
From `lib/adhearsion/call.rb`:

``` Ruby
    # @return [Time] the time at which the call began. For inbound calls this is the time at which the call was offered to Adhearsion. For outbound calls it is the time at which the remote party answered.
    attr_reader :start_time
```

This is inconsistent. I think this should be:
- For inbound calls, the time the call was offered to Adhearsion
- For outbound calls, the time at which the call was dialed

We can probably also add an `:answer_time` attribute which tracks the time at which the call was answered.

**Comment by emcgee** [comment]
:+1:
