### ISSUE TITLE
File IO bottlenecks

### ISSUE THREAD

**Issue by dwilkie** [adhearsion/adhearsion#611]
I've got an adhearsion app running on AWS (multi-container docker app), which is connected to a FreeSwitch instance. I'm having I/O issues when playing a file. When I have a few simultaneous calls I get an iowait bottleneck. Inspecting `iotop` I can see the AHN process is reading from disk.

I'm using httapi with file caching in FreeSwitch but it's the ANH processes which is reading from disk. Is it possible to read the file from memory instead? Does rayo read the file from FreeSwitch and save it locally?

**Comment by benlangfeld** [comment]
What file is Adhearsion reading?

**Comment by dwilkie** [comment]
Hi Ben, thanks for your reply. I've attached a screenshot of the output of `top`, and `iotop` when I'm having this issue. I've got adhearsion on trace level debugging but I can't see any output which shows the file it's reading.

For this particular call flow, it's just doing a `play_audio` with a URL. FreeSwitch is running on a different server, but on the same local network.

Do you have any pointers to figure out which file it's reading?

![io_top_adhearsion](https://cloud.githubusercontent.com/assets/127583/18984537/69210dd6-871d-11e6-9156-94d3e128a742.png)
![top_adhearsion](https://cloud.githubusercontent.com/assets/127583/18984536/69181078-871d-11e6-9235-bffa751d861f.png)

Edit:

Attached is another screenshot showing a `cat /proc/22936/io` and a `sudo lsof -p 22936`. As you can see it's read 49 GB and it looks like it's reading from a FIFO queue.

![adhearsion-cat-io](https://cloud.githubusercontent.com/assets/127583/18986341/9167de60-8726-11e6-9f4b-d579844c2dfb.png)

**Comment by bklang** [comment]
@dwilkie Are you using any EventSocket? Does this system have a very large volume of traffic (not necessarily all going to the Adhearsion app)?

**Comment by dwilkie** [comment]
Hi Ben, thanks for your help. I'm using sippy_cup to test a simple call flow which just plays an audio file which is ~ 2.5mb.

This problem is happening when I get to around 10-15 simultaneous calls.

The application is open source https://github.com/dwilkie/somleng it's being used in an early warning system for a NGO. As you can see in the https://github.com/dwilkie/somleng/blob/master/Gemfile I had to lock down EventMachine to 1.0.9 since I was getting segfaults with the latest version it resolves to. I'm not sure why this would be affecting I/O though.

Mod event_socket is installed in the FreeSwitch configuration https://github.com/dwilkie/freeswitch-config but I'm only using it to connect to the console for debugging in FreeSwitch.

Adhearsion is running in a docker container on its own elastic beanstalk instance. It's the only application that's running on that instance. FreeSwitch is running in another instance within the same VPC

**Comment by dwilkie** [comment]
I finally figured out the problem. The docker container was running out of it's allocated memory so it was (presumably) reading and writing from it's swap inside the container. This appears on the host as I/O wait. The key is to see what's happening inside docker with `sudo docker stats`. This shows memory allocated and IO inside the container.

Appreciate you guys helping look into it for me.
