### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by Syfer** [adhearsion/adhearsion#615]
Adhearsion is alive or dead ?

**Comment by lpradovera** [comment]
That is not a great question to ask. How does it look to you? Why do you think it's dead? Are you waiting on any feature?

**Comment by Syfer** [comment]
Yes, i know. Question is bad, but i'm waiting for release of 3-rd version, but i see that last commit was a long time ago.
Also i have a problem in 2.6.2 version that a cannot play any sound file into a bridged call:
i mean that when two participants are bridged via dial method i'm calling next code into confirmation class
`call.after 30.seconds do 
  play 'something' 
end`
but nothing happened. Methods like `call.unjoin` is working inside `call.after` but `play` don't. I hear that sound only after call is unbridged.
Main idea is to play a sound like "2 minutes left" into current bridge, to all participants (or only one, don't matter).
So i'm waiting 3-rd version, may be this will be possible there ... but maybe i'm doing somethig wrong.
Are help would be appreciated.
Thanks

**Comment by benlangfeld** [comment]
You can use the released 3.0.0.rc1 to test your bug, and if it persists, report it fully in an appropriately titled issue.

Adhearsion is alive, but the core team's attention is currently on other projects and Adhearsion's development is not as active as it used to be. The 3.0.0 full release is currently pending performance regression testing on a large app under mine and @bklang's control. There is, however, nothing preventing you from testing the RC and providing your feedback [as has previously been requested](https://groups.google.com/forum/#!topic/adhearsion/NTB-gSrLqQ0) and unfortunately lacked significant responses.

**Comment by lpradovera** [comment]
On the `3.0` release, Ben said it better than I could.

As for playing audio in a call, I am sorry but I do not remember which one between FreeSWITCH and Asterisk does *not* support that. What platform and version are you on?

**Comment by Syfer** [comment]
I'm on asterisk 11 (also tested on 13). I think that adhersion (or punchblock) is blocking that bridge and puts a `play` into a command queue

**Comment by lpradovera** [comment]
This would be better as a mailing list conversation, but in the meantime I can tell you that I am almost sure Asterisk does not play audio in a bridged call, while FreeSWITCH does.

**Comment by benlangfeld** [comment]
@Syfer Please test with Adhearsion 3 and file an issue which follows the issue guidelines clearly displayed above the form if the problem persists. Locking this ticket.
