### ISSUE TITLE
Exception events are triggered twice per exception

### ISSUE THREAD

**Issue by chewi** [adhearsion/adhearsion#618]
I noticed that Adhearsion (v3.0.0.rc1) always logs exceptions twice and I was wondering why that is. It seems to be because you're triggering `Adhearsion::Events.trigger :exception` twice, once in `CallController#bg_exec` via `catching_standard_errors` and once in `CallController#execute!`.

**Comment by benlangfeld** [comment]
We should probably remove this from `bg_exec`. I can't remember what side effects this might have if any, though.
