### ISSUE TITLE
Pinned nokogiri ~> 1.5 has 7 vulnerabilities

### ISSUE THREAD

**Issue by chewi** [adhearsion/adhearsion#621]
According to bundler-audit, this nokogiri version has 7 vulnerabilities, one of which is labelled High. It's not great seeing Adhearsion development stagnate but can we at least keep it secure? I know there have been issues with nokogiri in the past, is there a particular reason why it's pinned?

**Comment by emcgee** [comment]
Good point @chewi. As a quick test I just upgraded local versions of `blather` and `adhearsion` to `nokogiri` 1.8.0 and the test suites all passed 💯 

There is an issue with `eventmachine` > 1.0.9.1 on Debian (https://github.com/eventmachine/eventmachine/issues/670), so that would need to be pinned. 

There is also a Celluoid 0.17 branch, but it is currently failing a couple tests: https://github.com/adhearsion/adhearsion/tree/feature/celluloid-17

**Comment by chewi** [comment]
Unfortunately I have found a reason for the pin. It's adhearsion/blather#145. I really hoped that the issue would have gone away in more recent versions, especially as I believe Nokogiri is the reason Adhearsion crashes and burns when you try to restart it gracefully under JRuby. The bad news is that if anything, it's got even worse. 59 failures under 1.6.2, 73 failures under 1.8.1. Note that everything passes under MRI. I'll have a look but if @benlangfeld couldn't figure it out then I'm not too confident.

**Comment by emcgee** [comment]
@chewi Just to be clear, I forked and tested Blather with nokogiri `1.8.0` in my above comment and it passed all the specs (in MRI.) I never tested in JRuby :/

Only hold I found was (and still is) `eventmachine`.

**Comment by chewi** [comment]
Retest with JRuby and you'll see what I mean. That is a showstopper, we and many others are using JRuby.

**Comment by emcgee** [comment]
Yep - you're dead on. I updated that last comment to reflect the lack of JRuby testing.

**Comment by benlangfeld** [comment]
Nokogiri on JRuby stole several years of my life. It’s not a topic I’m willing to revisit, not is it one I suggest anyone else allow themselves to get sucked into. Nokogiri on MRI and JRuby are essentially separate projects with not the faintest guarantee of compatibility.

**Comment by chewi** [comment]
It looks like the additional failures are due to changes in JRuby rather than Nokogiri. JRuby 9.1.13.0 and 9.1.15.0 produce 16 failures even with Nokogiri 1.6.1.

**Comment by sodabrew** [comment]
Hi! Please try EventMachine 1.2.6, which has an important crash fix. https://github.com/eventmachine/eventmachine/releases/tag/v1.2.6
